### ISSUE TITLE
Not able to render background image and fonts specified in css in screenshot

### ISSUE THREAD

**Issue by ashisht99x** [corygibbons/component-image#3]
Hi @corygibbons,

I started using this lib for image comparision tests. My css has fonts and background images in it but while taking the screenshot both are missing. However normal static css is working fine. Can help with this?

my css looks like this:

.my_background_img {
  background: url('placeholderimage.png') no-repeat;
}

this background is not getting applied in the html but all other css is getting applied.

**Comment by corygibbons** [comment]
Hey @ashisht99x,

In this case `Puppeteer` doesn't have access to local files (GoogleChrome/puppeteer#1470). If you're able to to serve the files from somewhere it should work as expected.

```css
.my_background_img {
  background: url('http://localhost:1234/placeholderimage.png') no-repeat;
}
```

This may not be ideal but unfortunately I don't have any other suggestions at this point. If you figure out a way to make this work please let me know!
