### ISSUE TITLE
Fonts imported with @import are not loaded

### ISSUE THREAD

**Issue by apaatsio** [corygibbons/component-image#9]
I have fonts imported with CSS `@import` but the fonts are not in use in the generated image.

CSS:
```css
@import url('https://fonts.googleapis.com/css?family=Merriweather');
h1 {
  font-family: 'Merriweather';
}
```

When I generate image with React component `<h1>AaBbCc</h1>` the imported font is not visible in the image.
